export const APPOINTMENTORDERLIST_SET_LIST = 'APPOINTMENTORDERLIST_SET_LIST'

export const APPOINTMENTORDERLIST_SET__PARAM = 'APPOINTMENTORDERLIST_SET_PARAM'

export const APPOINTMENTORDERLIST_SET__PAGES = 'APPOINTMENTORDERLIST_SET_PAGES'






