
export const SET_SERVICE_HOURS_OBJ = 'SET_SERVICE_HOURS_OBJ'

export const SET_SUB_SERVICE_HOURS_LIST = 'SET_SUB_SERVICE_HOURS_LIST'

export const SET_MAIN_INFO = 'SET_MAIN_INFO'

export const SET_CAR_INFO = 'SET_CAR_INFO'

export const SET_QUERY_PARAMS = 'SET_QUERY_PARAMS'


