export const CHECKPLANLIST_SET_LIST = 'CHECKPLANLIST_SET_LIST'

export const CHECKPLANLIST_SET_CONDITION = 'CHECKPLANLIST_SET_CONDITION'

export const CHECKPLANLIST_SET_PAGE = 'CHECKPLANLIST_SET_PAGE'

