export const STAFFLIST_SET_LIST = 'STAFFLIST_SET_LIST'
export const STAFFLIST_SET__PAGE = 'STAFFLIST_SET__PAGE' 
export const STAFFLIST_GET__ORGNAME = 'STAFFLIST_GET__ORGNAME'

export const SET_STAFF_INFO = 'SET_STAFF_INFO'

export const GET_WORKTYPE = 'GET_WORKTYPE'
export const GET_WORKTYPE_LIST = 'GET_WORKTYPE_LIST'

export const GET_JOB_SYSET = 'GET_JOB_SYSET' //岗位关系码

export const GET_ORGCODES = 'GET_ORGCODES'

export const SET_JOBPAGE = 'SET_JOBPAGE'

export const SET_WORKPAGE = 'SET_WORKPAGE'

export const SET_QUERY = 'SET_QUERY'
