export const  STORE_REQUISITION_GET_ORDER_LIST = 'STORE_REQUISITION_GET_ORDER_LIST'
export const  STORE_REQUISITION_SET_PAGER = 'FINANCE_UPDATA_FINANCE'
export const  STORE_REQUISITION_GET_ORDER_TYPES = 'STORE_REQUISITION_GET_ORDER_TYPES'