export const WORKORDERLIST_SET_LIST = 'WORKORDERLIST_SET_LIST'

export const WORKORDERLIST_SET__PARAM = 'WORKORDERLIST_SET_PARAM'

export const WORKORDERLIST_SET__PAGES = 'WORKORDERLIST_SET_PAGES'

export const SET_PRICE_TYPE = 'SET_PRICE_TYPE'

export const SET_STORE_INFO = 'SET_STORE_INFO'

export const SET_WH_LIST = 'SET_WH_LIST'

export const SET_OPEN_SERVICE = 'SET_OPEN_SERVICE'





