export const PURCHASERETURNLIST_SET_LIST = 'PURCHASERETURNLIST_SET_LIST'

export const PURCHASERETURNLIST_SET__PARAM = 'PURCHASERETURNLIST_SET_PARAM'

export const PURCHASERETURNLIST_SET__PAGES = 'PURCHASERETURNLIST_SET_PAGES'

