export const SKUCARLIST_SET_LIST = 'SKUCARLIST_SET_LIST'

export const SKUCARLIST_SET__PARAM = 'SKUCARLIST_SET_PARAM'

export const SKUCARLIST_SET__PAGES = 'SKUCARLIST_SET_PAGES'


export const CARSKULIST_SET_LIST = 'CARSKULIST_SET_LIST'

export const CARSKULIST_SET__PARAM = 'CARSKULIST_SET_PARAM'

export const CARSKULIST_SET__PAGES = 'CARSKULIST_SET_PAGES'


export const  SKUCARALLLIST_SET_LIST = 'CARSKUALLLIST_SET_LIST'

export const  SKUCARALLLIST_SET__PARAM = 'CARSKUALLLIST_SET_PARAM'

export const  SKUCARALLLIST_SET__PAGES = 'CARSKUALLLIST_SET_PAGES'