export const SALEDISCOUNTLIST_SET_LIST = 'SALEDISCOUNTLIST_SET_LIST'

export const SALEDISCOUNTLIST_SET__PARAM = 'SALEDISCOUNTLIST_SET_PARAM'

export const SALEDISCOUNTLIST_SET__PAGES = 'SALEDISCOUNTLIST_SET_PAGES'

