export const PURCHASECONTRACTLIST_SET_LIST = 'PURCHASECONTRACTLIST_SET_LIST'

export const PURCHASECONTRACTLIST_SET__PARAM = 'PURCHASECONTRACTLIST_SET_PARAM'

export const PURCHASECONTRACTLIST_SET__PAGES = 'PURCHASECONTRACTLIST_SET_PAGES'

