// 门店自采管理
export const OWNPURCHASE_SET_LIST = 'OWNPURCHASE_SET_LIST'

export const OWNPURCHASE_SET__PARAM = 'OWNPURCHASE_SET_PARAM'

export const OWNPURCHASE_SET__PAGES = 'OWNPURCHASE_SET_PAGES'

export const OWNPURCHASE_SET__AdDDSKULIST = 'OWNPURCHASE_SET__AdDDSKULIST'

export const OWNPURCHASE_SET__ORDERNO = 'OWNPURCHASE_SET__ORDERNO'
