/**
 * create by lwx on 2018/05/04 17:00
 * @see 文件存放所有业务编码常量 ( 命名: 大写中间下划线 )
 *
 */

// 卡销售单业务编码
export const CARD_SALE_SORDER_SEQ = 'CARDSALESORDERSEQ'
// 卡销售单支付业务编码
export const CARD_SALE_PAYMENT_SEQ = 'CARDSALESPAYMENTSEQ'
// 卡销售单发票业务编码
export const CARD_SALE_INVOICE_SEQ = 'CARDSALESINVOICESEQ'
// 卡充值单号
export const CARD_RECHARGE_ORDER_SEQ = 'CARDRECHARGEORDERSEQ'
// 卡充值记录明细编码
export const CAED_RECHARGE_PAYMENT_SEQ = 'CARDRECHARGEPAYMENTSEQ'
// 卡充值记录发票信息业务编码
export const CAED_RECHARGE_INVOICE_SEQ = 'CARDRECHARGEINVOICESEQ'
// 检查模板明细编码
export const CHECK_TEMPLATE_SEQ = 'CHECKTEMPLATESEQ'
// 检查模板明细业务编码
export const CHECK_TEMPLATE_DETAIL_SEQ = 'CHECKTEMPLATEDETAILSEQ'
// 检查模板适用范围业务编码
export const CHECK_TEMPLATE_USERANGE_SEQ = 'CHECKTEMPLATEUSERANGESEQ'
// 检查模板明细的车型附加信息业务编码
export const CHECK_TEMPLATE_DETAIL_CARADD_SEQ = 'CHECKTEMPLATEDETAILCARADDSEQ'
// 红冲单号
export const REFUND_INVOICE_ORDER_SEQ = 'REFUNDINVOICEORDERSEQ'
// 退款退卡支付明细
export const CARD_REFUND_PAYMENT_SEQ = 'CARDREFUNDPAYMENTSEQ'
// 卡退卡退款单信息业务编码
export const CARD_REFUND_ORDER_SEQ = 'CARDREFUNDORDERSEQ'
// 客户主档信息业务编码
export const CUSTOM = 'CUSTOM'
// 客户车辆业务编码
export const CUSTOM_VEHICLE_SEQ  = 'CUSTOMVEHICLESEQ'
// 推荐服务业务编码
export const SERVICE_RECOMMENDATION_SEQ = 'SERVICERECOMMENDATIONSEQ'
// 客户车辆扩展信息业务编码
export const CUSTOM_VEHICLE_ADD_SEQ = 'CUSTOMVEHICLEADDSEQ'
// 促销折扣单信息业务编码
export const PROMOTION_DISCOUNT_ORDER_SEQ = 'PROMOTIONDISCOUNTORDERSEQ'
// 促销折扣规则业务编码
export const PROMOTION_DISCOUNT_RULE_SEQ = 'PROMOTIONDISCOUNTRULESEQ'
// 促销折扣明细业务编码
export const PROMOTION_DISCOUNT_RULE_DETAIL_SEQ = 'PROMOTIONDISCOUNTRULEDETAILSEQ'
// 库存调整单业务编码
export const STOCK_ADJUST_ORDER_SEQ = 'STOCKADJUSTORDERSEQ'
// 库存调整明细业务编码
export const STOCK_ADJUST_SKUDETAIL_SEQ = 'STOCKADJUSTSKUDETAILSEQ'
// 采购单明细
export const PODETAIL = 'PODETAIL'
// 对账核销单信息业务编码
export const RECONCILIATIONVERIFYORDERSEQ = 'RECONCILIATIONVERIFYORDERSEQ'
// 对账核销单付款业务编码
export const RECONCILIATIONVERIFYPAYMENTSEQ = 'RECONCILIATIONVERIFYPAYMENTSEQ'
// 采购退货单编码
export const RETURN_TO_SUPPLIEROR_DER_SEQ = 'RETURNTOSUPPLIERORDERSEQ'
// 采购退货主信息业务编码
export const PURCHASE_RETURN_ORDERINFO_SEQ = 'PURCHASERETURNORDERINFOSEQ'
// 采购退货明细信息业务编码
export const PURCHASE_RETURN_SKUDETAIL_SEQ = 'PURCHASERETURNSKUDETAILSEQ'
// 预检单结果信息业务编码
export const PRE_CHECK_ANSWER_SEQ = 'PRECHECKANSWERSEQ'
// 预检单信息业务编码
export const PRE_CHECK_ORDER_SEQ = 'PRECHECKORDERSEQ'
// 预检单推荐信息业务编码
export const PRE_CHECK_RECOMMENDATTON_SEQ = 'PRECHECKRECOMMENDATIONSEQ'
// 临时商品编码
export const SKU_TEMPCODE_SEQ = 'SKUTEMPCODESEQ'
// 订单支付流水业务编码
export const ORDERPAYMENTSEQ = 'ORDERPAYMENTSEQ'
// 服务工单明细业务编码	
export const SERVICE_ORDER_DETAIL_SEQ = 'SERVICEORDERDETAILSEQ'
// 托外订单明细业务编码	
export const OUTSIDE_ORDER_DETAIL_SEQ = 'OUTSIDEORDERDETAILSEQ'
// 商品摆放目录编码
export const SKU_LOCATION_INFO_SEQ = 'SKULOCATIONINFOSEQ'
// 券销售单信息业务编码
export const COUPON_SALES_ORDER_SEQ = 'COUPONSALESORDERSEQ'
// 券销售单明细业务编码
export const COUPON_SALES_DETAIL_SEQ = 'COUPONSALESDETAILSEQ'
// 券销售支付信息业务编码
export const COUPON_SALES_PAYMENT_SEQ = 'COUPONSALESPAYMENTSEQ'
// 	预约单服务明细信息编码
export const BOOK_ORDER_SERVICE_DETAIL_SEQ = 'BOOKORDERSERVICEDETAILSEQ'
